name: Work Guard Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Run Lint, Prettier, and Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Verifica o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Instala dependências
      - name: Install dependencies
        run: npm install

      # 4. Executa o Prettier
      - name: Run Prettier
        run: npm run prettier-check

      # 5. Executa o ESLint
      - name: Run ESLint
        run: npm run lint

      # 6. Executa os testes
      - name: Run Tests
        run: npm run test:unit
